version: 2

sources:
  - name: silver_schema  # Schema in the database
    description: "Cleaned data tables from bronze layer"
    schema: silver_schema   # The schema where the source tables exist
    tables:
      - name: customers_silver_layer
      - name: salestransactions_silver_layer
  



